# Generated by Django 6.1 on 2026-08-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_subscribe',
            new_name='is_subscribed',
        ),
    ]
