# Generated by Django 6.1 on 2026-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'г'), ('кг', 'кг'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт'), ('ст.л.', 'ст.л.'), ('ч.л.', 'ч.л.'), ('капля', 'капля'), ('кусок', 'кусок'), ('банка', 'банка'), ('стакан', 'стакан'), ('щепотка', 'щепотка'), ('горсть', 'горсть'), ('веточка', 'веточка'), ('батон', 'батон')], max_length=40, verbose_name='Измерение'),
        ),
    ]
