# Generated by Django 6.1 on 2026-08-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_is_favorited_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': ('рецепт',), 'verbose_name_plural': 'рецепты'},
        ),
    ]
