# Generated by Django 6.1 on 2026-08-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_user_is_subscribed_subscritions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscritions',
            new_name='Subscrition',
        ),
    ]
