# Generated by Django 6.1 on 2026-08-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_rename_subscritions_subscrition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscrition',
            new_name='Subscription',
        ),
    ]
