# Generated by Django 6.1 on 2026-08-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
